# Use postgres/example user/password credentials
version: '3.1'

services:
  db-prod:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: proflex
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/sql_scripts:/sql_scripts
      - ./app/postgres-data:/var/lib/postgresql/data

  webshop:
    image: nokacper24/g4webshop:1.0
    ports:
      - "8080:8080"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      ALLOWED_ORIGINS: https://127.0.0.1:8080,https://localhost:8080,https://localhost:5173,https://127.0.0.1:5173
      DATABASE_URL: postgresql://postgres:password@db-prod:5432/proflex
      CERT_PATH: /certs/certificate.pem
      PRIV_KEY_PATH: /certs/privatekey.pem
    depends_on:
      - db-prod
    volumes:
      - ./app:/webshop
      - ./app/certs:/certs
    restart: always