# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: proflex
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql_scripts:/sql_scripts
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080