pub enum PostgresDBError {
    successful_completion,
    warning,
    dynamic_result_sets_returned,
    implicit_zero_bit_padding,
    null_value_eliminated_in_set_function,
    privilege_not_granted,
    privilege_not_revoked,
    string_data_right_truncation,
    deprecated_feature,
    no_data,
    no_additional_dynamic_result_sets_returned,
    sql_statement_not_yet_complete,
    connection_exception,
    connection_does_not_exist,
    connection_failure,
    sqlclient_unable_to_establish_sqlconnection,
    sqlserver_rejected_establishment_of_sqlconnection,
    transaction_resolution_unknown,
    protocol_violation,
    triggered_action_exception,
    feature_not_supported,
    invalid_transaction_initiation,
    locator_exception,
    invalid_locator_specification,
    invalid_grantor,
    invalid_grant_operation,
    invalid_role_specification,
    diagnostics_exception,
    stacked_diagnostics_accessed_without_active_handler,
    case_not_found,
    cardinality_violation,
    data_exception,
    array_subscript_error,
    character_not_in_repertoire,
    datetime_field_overflow,
    division_by_zero,
    error_in_assignment,
    escape_character_conflict,
    indicator_overflow,
    interval_field_overflow,
    invalid_argument_for_logarithm,
    invalid_argument_for_ntile_function,
    invalid_argument_for_nth_value_function,
    invalid_argument_for_power_function,
    invalid_argument_for_width_bucket_function,
    invalid_character_value_for_cast,
    invalid_datetime_format,
    invalid_escape_character,
    invalid_escape_octet,
    invalid_escape_sequence,
    nonstandard_use_of_escape_character,
    invalid_indicator_parameter_value,
    invalid_parameter_value,
    invalid_preceding_or_following_size,
    invalid_regular_expression,
    invalid_row_count_in_limit_clause,
    invalid_row_count_in_result_offset_clause,
    invalid_tablesample_argument,
    invalid_tablesample_repeat,
    invalid_time_zone_displacement_value,
    invalid_use_of_escape_character,
    most_specific_type_mismatch,
    null_value_not_allowed,
    null_value_no_indicator_parameter,
    numeric_value_out_of_range,
    sequence_generator_limit_exceeded,
    string_data_length_mismatch,
    substring_error,
    trim_error,
    unterminated_c_string,
    zero_length_character_string,
    floating_point_exception,
    invalid_text_representation,
    invalid_binary_representation,
    bad_copy_file_format,
    untranslatable_character,
    not_an_xml_document,
    invalid_xml_document,
    invalid_xml_content,
    invalid_xml_comment,
    invalid_xml_processing_instruction,
    duplicate_json_object_key_value,
    invalid_argument_for_sql_json_datetime_function,
    invalid_json_text,
    invalid_sql_json_subscript,
    more_than_one_sql_json_item,
    no_sql_json_item,
    non_numeric_sql_json_item,
    non_unique_keys_in_a_json_object,
    singleton_sql_json_item_required,
    sql_json_array_not_found,
    sql_json_member_not_found,
    sql_json_number_not_found,
    sql_json_object_not_found,
    too_many_json_array_elements,
    too_many_json_object_members,
    sql_json_scalar_required,
    sql_json_item_cannot_be_cast_to_target_type,
    integrity_constraint_violation,
    restrict_violation,
    not_null_violation,
    foreign_key_violation,
    unique_violation,
    check_violation,
    exclusion_violation,
    invalid_cursor_state,
    invalid_transaction_state,
    active_sql_transaction,
    branch_transaction_already_active,
    held_cursor_requires_same_isolation_level,
    inappropriate_access_mode_for_branch_transaction,
    inappropriate_isolation_level_for_branch_transaction,
    no_active_sql_transaction_for_branch_transaction,
    read_only_sql_transaction,
    schema_and_data_statement_mixing_not_supported,
    no_active_sql_transaction,
    in_failed_sql_transaction,
    idle_in_transaction_session_timeout,
    invalid_sql_statement_name,
    triggered_data_change_violation,
    invalid_authorization_specification,
    invalid_password,
    dependent_privilege_descriptors_still_exist,
    dependent_objects_still_exist,
    invalid_transaction_termination,
    sql_routine_exception,
    function_executed_no_return_statement,
    modifying_sql_data_not_permitted,
    prohibited_sql_statement_attempted,
    reading_sql_data_not_permitted,
    invalid_cursor_name,
    external_routine_exception,
    containing_sql_not_permitted,
    external_routine_invocation_exception,
    invalid_sqlstate_returned,
    trigger_protocol_violated,
    srf_protocol_violated,
    event_trigger_protocol_violated,
    savepoint_exception,
    invalid_savepoint_specification,
    invalid_catalog_name,
    invalid_schema_name,
    transaction_rollback,
    transaction_integrity_constraint_violation,
    serialization_failure,
    statement_completion_unknown,
    deadlock_detected,
    syntax_error_or_access_rule_violation,
    syntax_error,
    insufficient_privilege,
    cannot_coerce,
    grouping_error,
    windowing_error,
    invalid_recursion,
    invalid_foreign_key,
    invalid_name,
    name_too_long,
    reserved_name,
    datatype_mismatch,
    indeterminate_datatype,
    collation_mismatch,
    indeterminate_collation,
    wrong_object_type,
    generated_always,
    undefined_column,
    undefined_function,
    undefined_table,
    undefined_parameter,
    undefined_object,
    duplicate_column,
    duplicate_cursor,
    duplicate_database,
    duplicate_function,
    duplicate_prepared_statement,
    duplicate_schema,
    duplicate_table,
    duplicate_alias,
    duplicate_object,
    ambiguous_column,
    ambiguous_function,
    ambiguous_parameter,
    ambiguous_alias,
    invalid_column_reference,
    invalid_column_definition,
    invalid_cursor_definition,
    invalid_database_definition,
    invalid_function_definition,
    invalid_prepared_statement_definition,
    invalid_schema_definition,
    invalid_table_definition,
    invalid_object_definition,
    with_check_option_violation,
    insufficient_resources,
    disk_full,
    out_of_memory,
    too_many_connections,
    configuration_limit_exceeded,
    program_limit_exceeded,
    statement_too_complex,
    too_many_columns,
    too_many_arguments,
    object_not_in_prerequisite_state,
    object_in_use,
    cant_change_runtime_param,
    lock_not_available,
    unsafe_new_enum_value_usage,
    operator_intervention,
    query_canceled,
    admin_shutdown,
    crash_shutdown,
    cannot_connect_now,
    database_dropped,
    idle_session_timeout,
    system_error,
    io_error,
    undefined_file,
    duplicate_file,
    snapshot_too_old,
    config_file_error,
    lock_file_exists,
    fdw_error,
    fdw_column_name_not_found,
    fdw_dynamic_parameter_value_needed,
    fdw_function_sequence_error,
    fdw_inconsistent_descriptor_information,
    fdw_invalid_attribute_value,
    fdw_invalid_column_name,
    fdw_invalid_column_number,
    fdw_invalid_data_type,
    fdw_invalid_data_type_descriptors,
    fdw_invalid_descriptor_field_identifier,
    fdw_invalid_handle,
    fdw_invalid_option_index,
    fdw_invalid_option_name,
    fdw_invalid_string_length_or_buffer_length,
    fdw_invalid_string_format,
    fdw_invalid_use_of_null_pointer,
    fdw_too_many_handles,
    fdw_out_of_memory,
    fdw_no_schemas,
    fdw_option_name_not_found,
    fdw_reply_handle,
    fdw_schema_not_found,
    fdw_table_not_found,
    fdw_unable_to_create_execution,
    fdw_unable_to_create_reply,
    fdw_unable_to_establish_connection,
    plpgsql_error,
    raise_exception,
    no_data_found,
    too_many_rows,
    assert_failure,
    internal_error,
    data_corrupted,
    index_corrupted,
    NoErrorCode,
}

impl PostgresDBError {
    pub fn from_str(error: Box<dyn sqlx::error::DatabaseError>) -> Self {
        match error.code() {
            Some(e) => match e.as_ref() {
                "00000" => Self::successful_completion,
                "01000" => Self::warning,
                "0100C" => Self::dynamic_result_sets_returned,
                "01008" => Self::implicit_zero_bit_padding,
                "01003" => Self::null_value_eliminated_in_set_function,
                "01007" => Self::privilege_not_granted,
                "01006" => Self::privilege_not_revoked,
                "01004" => Self::string_data_right_truncation,
                "01P01" => Self::deprecated_feature,
                "02000" => Self::no_data,
                "02001" => Self::no_additional_dynamic_result_sets_returned,
                "03000" => Self::sql_statement_not_yet_complete,
                "08000" => Self::connection_exception,
                "08003" => Self::connection_does_not_exist,
                "08006" => Self::connection_failure,
                "08001" => Self::sqlclient_unable_to_establish_sqlconnection,
                "08004" => Self::sqlserver_rejected_establishment_of_sqlconnection,
                "08007" => Self::transaction_resolution_unknown,
                "08P01" => Self::protocol_violation,
                "09000" => Self::triggered_action_exception,
                "0A000" => Self::feature_not_supported,
                "0B000" => Self::invalid_transaction_initiation,
                "0F000" => Self::locator_exception,
                "0F001" => Self::invalid_locator_specification,
                "0L000" => Self::invalid_grantor,
                "0LP01" => Self::invalid_grant_operation,
                "0P000" => Self::invalid_role_specification,
                "0Z000" => Self::diagnostics_exception,
                "0Z002" => Self::stacked_diagnostics_accessed_without_active_handler,
                "20000" => Self::case_not_found,
                "21000" => Self::cardinality_violation,
                "22000" => Self::data_exception,
                "2202E" => Self::array_subscript_error,
                "22021" => Self::character_not_in_repertoire,
                "22008" => Self::datetime_field_overflow,
                "22012" => Self::division_by_zero,
                "22005" => Self::error_in_assignment,
                "2200B" => Self::escape_character_conflict,
                "22022" => Self::indicator_overflow,
                "22015" => Self::interval_field_overflow,
                "2201E" => Self::invalid_argument_for_logarithm,
                "22014" => Self::invalid_argument_for_ntile_function,
                "22016" => Self::invalid_argument_for_nth_value_function,
                "2201F" => Self::invalid_argument_for_power_function,
                "2201G" => Self::invalid_argument_for_width_bucket_function,
                "22018" => Self::invalid_character_value_for_cast,
                "22007" => Self::invalid_datetime_format,
                "22019" => Self::invalid_escape_character,
                "2200D" => Self::invalid_escape_octet,
                "22025" => Self::invalid_escape_sequence,
                "22P06" => Self::nonstandard_use_of_escape_character,
                "22010" => Self::invalid_indicator_parameter_value,
                "22023" => Self::invalid_parameter_value,
                "22013" => Self::invalid_preceding_or_following_size,
                "2201B" => Self::invalid_regular_expression,
                "2201W" => Self::invalid_row_count_in_limit_clause,
                "2201X" => Self::invalid_row_count_in_result_offset_clause,
                "2202H" => Self::invalid_tablesample_argument,
                "2202G" => Self::invalid_tablesample_repeat,
                "22009" => Self::invalid_time_zone_displacement_value,
                "2200C" => Self::invalid_use_of_escape_character,
                "2200G" => Self::most_specific_type_mismatch,
                "22004" => Self::null_value_not_allowed,
                "22002" => Self::null_value_no_indicator_parameter,
                "22003" => Self::numeric_value_out_of_range,
                "2200H" => Self::sequence_generator_limit_exceeded,
                "22026" => Self::string_data_length_mismatch,
                "22001" => Self::string_data_right_truncation,
                "22011" => Self::substring_error,
                "22027" => Self::trim_error,
                "22024" => Self::unterminated_c_string,
                "2200F" => Self::zero_length_character_string,
                "22P01" => Self::floating_point_exception,
                "22P02" => Self::invalid_text_representation,
                "22P03" => Self::invalid_binary_representation,
                "22P04" => Self::bad_copy_file_format,
                "22P05" => Self::untranslatable_character,
                "2200L" => Self::not_an_xml_document,
                "2200M" => Self::invalid_xml_document,
                "2200N" => Self::invalid_xml_content,
                "2200S" => Self::invalid_xml_comment,
                "2200T" => Self::invalid_xml_processing_instruction,
                "22030" => Self::duplicate_json_object_key_value,
                "22031" => Self::invalid_argument_for_sql_json_datetime_function,
                "22032" => Self::invalid_json_text,
                "22033" => Self::invalid_sql_json_subscript,
                "22034" => Self::more_than_one_sql_json_item,
                "22035" => Self::no_sql_json_item,
                "22036" => Self::non_numeric_sql_json_item,
                "22037" => Self::non_unique_keys_in_a_json_object,
                "22038" => Self::singleton_sql_json_item_required,
                "22039" => Self::sql_json_array_not_found,
                "2203A" => Self::sql_json_member_not_found,
                "2203B" => Self::sql_json_number_not_found,
                "2203C" => Self::sql_json_object_not_found,
                "2203D" => Self::too_many_json_array_elements,
                "2203E" => Self::too_many_json_object_members,
                "2203F" => Self::sql_json_scalar_required,
                "2203G" => Self::sql_json_item_cannot_be_cast_to_target_type,
                "23000" => Self::integrity_constraint_violation,
                "23001" => Self::restrict_violation,
                "23502" => Self::not_null_violation,
                "23503" => Self::foreign_key_violation,
                "23505" => Self::unique_violation,
                "23514" => Self::check_violation,
                "23P01" => Self::exclusion_violation,
                "24000" => Self::invalid_cursor_state,
                "25000" => Self::invalid_transaction_state,
                "25001" => Self::active_sql_transaction,
                "25002" => Self::branch_transaction_already_active,
                "25008" => Self::held_cursor_requires_same_isolation_level,
                "25003" => Self::inappropriate_access_mode_for_branch_transaction,
                "25004" => Self::inappropriate_isolation_level_for_branch_transaction,
                "25005" => Self::no_active_sql_transaction_for_branch_transaction,
                "25006" => Self::read_only_sql_transaction,
                "25007" => Self::schema_and_data_statement_mixing_not_supported,
                "25P01" => Self::no_active_sql_transaction,
                "25P02" => Self::in_failed_sql_transaction,
                "25P03" => Self::idle_in_transaction_session_timeout,
                "26000" => Self::invalid_sql_statement_name,
                "27000" => Self::triggered_data_change_violation,
                "28000" => Self::invalid_authorization_specification,
                "28P01" => Self::invalid_password,
                "2B000" => Self::dependent_privilege_descriptors_still_exist,
                "2BP01" => Self::dependent_objects_still_exist,
                "2D000" => Self::invalid_transaction_termination,
                "2F000" => Self::sql_routine_exception,
                "2F005" => Self::function_executed_no_return_statement,
                "2F002" => Self::modifying_sql_data_not_permitted,
                "2F003" => Self::prohibited_sql_statement_attempted,
                "2F004" => Self::reading_sql_data_not_permitted,
                "34000" => Self::invalid_cursor_name,
                "38000" => Self::external_routine_exception,
                "38001" => Self::containing_sql_not_permitted,
                "38002" => Self::modifying_sql_data_not_permitted,
                "38003" => Self::prohibited_sql_statement_attempted,
                "38004" => Self::reading_sql_data_not_permitted,
                "39000" => Self::external_routine_invocation_exception,
                "39001" => Self::invalid_sqlstate_returned,
                "39004" => Self::null_value_not_allowed,
                "39P01" => Self::trigger_protocol_violated,
                "39P02" => Self::srf_protocol_violated,
                "39P03" => Self::event_trigger_protocol_violated,
                "3B000" => Self::savepoint_exception,
                "3B001" => Self::invalid_savepoint_specification,
                "3D000" => Self::invalid_catalog_name,
                "3F000" => Self::invalid_schema_name,
                "40000" => Self::transaction_rollback,
                "40002" => Self::transaction_integrity_constraint_violation,
                "40001" => Self::serialization_failure,
                "40003" => Self::statement_completion_unknown,
                "40P01" => Self::deadlock_detected,
                "42000" => Self::syntax_error_or_access_rule_violation,
                "42601" => Self::syntax_error,
                "42501" => Self::insufficient_privilege,
                "42846" => Self::cannot_coerce,
                "42803" => Self::grouping_error,
                "42P20" => Self::windowing_error,
                "42P19" => Self::invalid_recursion,
                "42830" => Self::invalid_foreign_key,
                "42602" => Self::invalid_name,
                "42622" => Self::name_too_long,
                "42939" => Self::reserved_name,
                "42804" => Self::datatype_mismatch,
                "42P18" => Self::indeterminate_datatype,
                "42P21" => Self::collation_mismatch,
                "42P22" => Self::indeterminate_collation,
                "42809" => Self::wrong_object_type,
                "428C9" => Self::generated_always,
                "42703" => Self::undefined_column,
                "42883" => Self::undefined_function,
                "42P01" => Self::undefined_table,
                "42P02" => Self::undefined_parameter,
                "42704" => Self::undefined_object,
                "42701" => Self::duplicate_column,
                "42P03" => Self::duplicate_cursor,
                "42P04" => Self::duplicate_database,
                "42723" => Self::duplicate_function,
                "42P05" => Self::duplicate_prepared_statement,
                "42P06" => Self::duplicate_schema,
                "42P07" => Self::duplicate_table,
                "42712" => Self::duplicate_alias,
                "42710" => Self::duplicate_object,
                "42702" => Self::ambiguous_column,
                "42725" => Self::ambiguous_function,
                "42P08" => Self::ambiguous_parameter,
                "42P09" => Self::ambiguous_alias,
                "42P10" => Self::invalid_column_reference,
                "42611" => Self::invalid_column_definition,
                "42P11" => Self::invalid_cursor_definition,
                "42P12" => Self::invalid_database_definition,
                "42P13" => Self::invalid_function_definition,
                "42P14" => Self::invalid_prepared_statement_definition,
                "42P15" => Self::invalid_schema_definition,
                "42P16" => Self::invalid_table_definition,
                "42P17" => Self::invalid_object_definition,
                "44000" => Self::with_check_option_violation,
                "53000" => Self::insufficient_resources,
                "53100" => Self::disk_full,
                "53200" => Self::out_of_memory,
                "53300" => Self::too_many_connections,
                "53400" => Self::configuration_limit_exceeded,
                "54000" => Self::program_limit_exceeded,
                "54001" => Self::statement_too_complex,
                "54011" => Self::too_many_columns,
                "54023" => Self::too_many_arguments,
                "55000" => Self::object_not_in_prerequisite_state,
                "55006" => Self::object_in_use,
                "55P02" => Self::cant_change_runtime_param,
                "55P03" => Self::lock_not_available,
                "55P04" => Self::unsafe_new_enum_value_usage,
                "57000" => Self::operator_intervention,
                "57014" => Self::query_canceled,
                "57P01" => Self::admin_shutdown,
                "57P02" => Self::crash_shutdown,
                "57P03" => Self::cannot_connect_now,
                "57P04" => Self::database_dropped,
                "57P05" => Self::idle_session_timeout,
                "58000" => Self::system_error,
                "58030" => Self::io_error,
                "58P01" => Self::undefined_file,
                "58P02" => Self::duplicate_file,
                "72000" => Self::snapshot_too_old,
                "F0000" => Self::config_file_error,
                "F0001" => Self::lock_file_exists,
                "HV000" => Self::fdw_error,
                "HV005" => Self::fdw_column_name_not_found,
                "HV002" => Self::fdw_dynamic_parameter_value_needed,
                "HV010" => Self::fdw_function_sequence_error,
                "HV021" => Self::fdw_inconsistent_descriptor_information,
                "HV024" => Self::fdw_invalid_attribute_value,
                "HV007" => Self::fdw_invalid_column_name,
                "HV008" => Self::fdw_invalid_column_number,
                "HV004" => Self::fdw_invalid_data_type,
                "HV006" => Self::fdw_invalid_data_type_descriptors,
                "HV091" => Self::fdw_invalid_descriptor_field_identifier,
                "HV00B" => Self::fdw_invalid_handle,
                "HV00C" => Self::fdw_invalid_option_index,
                "HV00D" => Self::fdw_invalid_option_name,
                "HV090" => Self::fdw_invalid_string_length_or_buffer_length,
                "HV00A" => Self::fdw_invalid_string_format,
                "HV009" => Self::fdw_invalid_use_of_null_pointer,
                "HV014" => Self::fdw_too_many_handles,
                "HV001" => Self::fdw_out_of_memory,
                "HV00P" => Self::fdw_no_schemas,
                "HV00J" => Self::fdw_option_name_not_found,
                "HV00K" => Self::fdw_reply_handle,
                "HV00Q" => Self::fdw_schema_not_found,
                "HV00R" => Self::fdw_table_not_found,
                "HV00L" => Self::fdw_unable_to_create_execution,
                "HV00M" => Self::fdw_unable_to_create_reply,
                "HV00N" => Self::fdw_unable_to_establish_connection,
                "P0000" => Self::plpgsql_error,
                "P0001" => Self::raise_exception,
                "P0002" => Self::no_data_found,
                "P0003" => Self::too_many_rows,
                "P0004" => Self::assert_failure,
                "XX000" => Self::internal_error,
                "XX001" => Self::data_corrupted,
                "XX002" => Self::index_corrupted,
            },
            None => Self::NoErrorCode,
        }
    }
}
