[package]
name = "webshop_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-session = "0.7.2"
actix-web = "4.2.1"
diesel = {version="2.0.2", features=["postgres", "r2d2"]}
serde = "1.0.152"
serde_json = "1.0.91"
