name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:

    runs-on: ubuntu-latest

    environment: env_vars_db

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd webshop_server && cargo build --verbose
    - name: Run tests
      run: cd webshop_server && cargo test --verbose
